version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless...
      - yarn global add serverless
  build:
    commands:
      - yarn
      - cd api/ && yarn && yarn build && cd ../client && yarn && yarn build
      - cd ../
  post_build:
    commands:
      - echo Deploying with Serverless Framework
      - sls deploy -v -s $ENV_NAME