version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless...
      - yarn global add serverless
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - echo Deploying with Serverless Framework
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`
      - cd api/ && yarn && yarn build && cd ../client && yarn && yarn build
      -  cd ../