version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless...
      - yarn global add serverless
      - yarn global add rimraf
  pre_build:
    commands:
      - yarn
      - cd api/ && yarn && yarn build
      - rimraf node_modules
      - rimraf src
      - rimraf test
      - cd ../client && yarn && yarn build
      - rimraf src
      - rimraf public
      - rimraf node_modules
      - rimraf test
      - cd ../
  build:
    commands:
      - echo Deploying with Serverless Framework
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`