service:
  name: serverless-nest
app: serverless-nest

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: api/dist/main.handler
    events:
      - httpApi: '*'