service:
  name: serverless-nest
app: serverless-nest

plugins:
  - serverless-offline
  - serverless-plugin-scripts
  

package:
  excludeDevDependencies: true
  exclude:
    - api/src/**
    - api/node_modules/**
    - api/test/**
    - client/node_modules/**
    - client/public/**
    - client/src/**
    - node_modules/**
  include:
    - api/dist/**
    - client/build/**

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: api/dist/main.handler
    events:
      - httpApi: '*'

custom:
  scripts:
    hooks:
      'deploy:finalize': yarn && cd api && yarn && cd ../client && yarn
